<?php

$dbPath = __DIR__ . '/banco.sqlite';
$pdo = new PDO("sqlite:$dbPath");

$pdo->exec('ALTER TABLE videos ADD COLUMN image_path TXT');


{
    "name": "angle",
    "version": "0.0.0",
    "description": "Angle - Bootstrap Admin Template",
    "author": "@themicon_co",
    "license": "https://wrapbootstrap.com/help/licenses",
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "modernizr": "modernizr -c modernizr-config.json -d node_modules/modernizr/modernizr.custom.js",
        "postinstall": "npm run modernizr",
        "rtlcss": "rtlcss"
    },
    "dependencies": {
        "@fortawesome/fontawesome-free": "5.5.0",
        "@ttskch/select2-bootstrap4-theme": "1.0.4",
        "animate.css": "3.7.0",
        "axios": "0.19.0",
        "bootstrap": "4.3.1",
        "bootstrap-colorpicker": "3.1.2",
        "bootstrap-datepicker": "1.8.0",
        "bootstrap-filestyle": "github:markusslima/bootstrap-filestyle#v2.1.0",
        "bootstrap-slider": "10.2.3",
        "bootstrap-tagsinput": "github:bootstrap-tagsinput/bootstrap-tagsinput#0.8.0",
        "bootstrap-wysiwyg": "2.0.1",
        "chart.js": "2.7.3",
        "chartist": "0.11.0",
        "chosen-js": "1.8.7",
        "components-jqueryui": "github:components/jqueryui",
        "cropper": "4.0.0",
        "d3": "3.5.16",
        "datatables.net": "1.10.19",
        "datatables.net-bs": "1.10.19",
        "datatables.net-bs4": "1.10.19",
        "datatables.net-buttons": "1.5.4",
        "datatables.net-buttons-bs": "1.5.4",
        "datatables.net-keytable": "2.5.0",
        "datatables.net-keytable-bs": "2.5.0",
        "datatables.net-responsive": "2.2.3",
        "datatables.net-responsive-bs": "2.2.3",
        "dropzone": "5.5.1",
        "easy-pie-chart": "2.1.7",
        "fastclick": "1.0.6",
        "flot": "github:themicon/flot",
        "fullcalendar": "3.9.0",
        "html5sortable": "0.9.8",
        "i18next": "12.0.0",
        "i18next-xhr-backend": "1.5.1",
        "ika.jvectormap": "github:themicon/ika.jvectormap",
        "inputmask": "4.0.3",
        "jqcloud2": "2.0.3",
        "jquery": "3.4.1",
        "jquery-bootgrid": "1.3.1",
        "jquery-knob": "1.2.11",
        "jquery-slimscroll": "1.3.8",
        "jquery-sparkline": "2.4.0",
        "jquery-steps": "1.1.0",
        "jquery-ui-touch-punch": "0.2.3",
        "jquery-validation": "1.18.0",
        "jquery.easing": "1.4.1",
        "jquery.flot.spline": "github:themicon/jquery.flot.spline",
        "jquery.flot.tooltip": "github:krzysu/flot.tooltip",
        "jquery.gmap": "github:marioestrada/jQuery-gMap",
        "js-storage": "1.0.4",
        "jszip": "3.1.5",
        "loaders.css": "0.1.2",
        "matchmedia": "0.1.2",
        "modernizr": "3.7.1",
        "moment": "2.22.2",
        "morris.js.so": "0.5.1",
        "nestable": "github:themicon/nestable",
        "parsleyjs": "2.8.1",
        "pdfmake": "0.1.56",
        "popper.js": "^1.15.0",
        "raphael": "2.2.7",
        "rickshaw": "1.6.6",
        "screenfull": "3.3.3",
        "select2": "4.0.6-rc.1",
        "simple-line-icons": "2.4.1",
        "spinkit": "1.2.5",
        "sweetalert": "2.1.2",
        "weather-icons": "github:erikflowers/weather-icons",
        "whirl": "github:themicon/whirl",
        "x-editable": "1.5.1"
    },
    "devDependencies": {
        "bootstrap": "^4.0.0",
        "cross-env": "5.1",
        "globby": "9.2.0",
        "imports-loader": "0.8.0",
        "jquery": "^3.2",
        "laravel-mix": "4.0.7",
        "laravel-mix-bundle-analyzer": "1.0.2",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "rtlcss": "2.4.0",
        "sass": "^1.20.1",
        "sass-loader": "7.*",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    }
}




como resolver esse problema ,Your requirements could not be resolved to an installable set of packages. Problem 1 - Root composer.json requires php ^8.1 but your php version (7.2.34) does not satisfy that requirement. Problem 2 - Root composer.json requires laravel/sanctum ^3.2 -> satisfiable by laravel/sanctum[v3.2.0, ..., v3.2.5]. - laravel/sanctum[v3.2.0, ..., v3.2.5] require php ^8.0.2 -> your php version (7.2.34) does not satisfy that requirement. Problem 3 - laravel/framework[v10.8.0, ..., v10.9.0] require php ^8.1 -> your php version (7.2.34) does not satisfy that requirement. - Root composer.json requires laravel/framework ^10.8 -> satisfiable by laravel/framework[v10.8.0, v10.9.0].
